// swift-tools-version:5.9
import PackageDescription

// Local Swift package that wraps the Rust staticlib (`Zuko.xcframework`,
// built by `scripts/build-ffi.sh`) + the uniffi-generated Swift bindings
// (`Sources/ZukoFFI/ZukoFFI.swift`, regenerated by the same script).
//
// The iOS app references this as a local package in `project.yml`:
//   packages:
//     ZukoFFI:
//       path: ../ZukoFFI
//
// The XCFramework is gitignored (rebuilt on demand by build-ffi.sh or CI).
// The Swift bindings are committed (deterministic output — the same FFI
// always generates the same Swift). If you change `src/ffi.rs`, re-run
// `sh scripts/build-ffi.sh` to regenerate both.

let package = Package(
    name: "ZukoFFI",
    platforms: [
        // Must match iroh-ffi's floor: the N0 relay stack (nw_path_is_ultra_constrained)
        // needs iOS 17.5.
        .iOS("17.5"),
    ],
    products: [
        .library(
            name: "ZukoFFI",
            targets: ["ZukoFFI", "Zuko"]),
    ],
    dependencies: [],
    targets: [
        // The binary target wraps the prebuilt XCFramework (the Rust staticlib
        // + C headers + modulemap). Named `Zuko` to match the framework name
        // inside the XCFramework, so the `import zukoFFI` sub-module resolves
        // through its modulemap.
        .binaryTarget(
            name: "Zuko",
            path: "Zuko.xcframework"),
        // The source target compiles the uniffi-generated Swift bindings
        // (`ZukoFFI.swift`), which call the C FFI functions from the binary
        // target. This is what the iOS app imports: `import ZukoFFI`.
        .target(
            name: "ZukoFFI",
            dependencies: [
                .byName(name: "Zuko"),
            ],
            path: "Sources/ZukoFFI",
            linkerSettings: [
                // iroh's deps need Network.framework on iOS (nw_interface_get_index).
                .linkedFramework("Network"),
            ]),
    ]
)
