#!/bin/sh
# zuko host installer.
#
# Prerequisite: mise  (https://mise.jdx.dev)
#   install it first:  curl https://mise.run | sh
#
# This installs the latest `zuko` release from GitHub via mise's `github:`
# backend (a single binary that does both `zuko host` and `zuko connect`), then
# sets up a persistent background service for the host mode
# (systemd user unit on Linux, launchd on macOS).
#
#   curl -fsSL https://raw.githubusercontent.com/adonm/zuko/main/zuko/scripts/install.sh | sh
#
# Environment overrides:
#   ZUKO_VERSION   release to install     (default: latest)
#   ZUKO_KEY       secret key path        (default: $HOME/.config/zuko/key)
#   ZUKO_SHELL     shell to launch        (default: $SHELL)
#   ZUKO_PREFIX    install prefix         (default: $HOME/.local)
set -eu

VERSION="${ZUKO_VERSION:-latest}"
KEY="${ZUKO_KEY:-${HOME}/.config/zuko/key}"
SHELL_CMD="${ZUKO_SHELL:-${SHELL:-/bin/bash}}"
PREFIX="${ZUKO_PREFIX:-${HOME}/.local}"

need() {
    command -v "$1" >/dev/null 2>&1 || {
        echo "missing prerequisite: $1" >&2
        [ "$1" = mise ] && echo "  install mise:  curl https://mise.run | sh" >&2
        exit 1
    }
}
need mise

OS="$(uname -s)"

# Make the key path absolute & ensure config/prefix dirs exist.
KEY="$(readlink -f "$KEY" 2>/dev/null || echo "$KEY")"
mkdir -p "$(dirname "$KEY")" "$PREFIX/bin"

echo "==> installing zuko@$VERSION from github:adonm/zuko via mise"
# `mise use --global` records the tool in the user config and installs it.
mise use --global "github:adonm/zuko@${VERSION}"

# Resolve the installed binary (a mise shim, named after the binary).
if ! BIN="$(command -v zuko 2>/dev/null || mise which zuko 2>/dev/null)"; then
    echo "mise installed zuko but it isn't on PATH." >&2
    echo "ensure mise shims are activated:  eval \"\$(mise activate zsh)\"  (or bash/fish)" >&2
    exit 1
fi
echo "==> installed $BIN"

# A stable wrapper the service unit points at, so it never needs to know about
# mise. It calls the resolved shim directly in host mode.
RUN="$PREFIX/bin/zuko-host-run"
cat >"$RUN" <<EOF
#!/bin/sh
# Generated by zuko install.sh. Edit to taste. Runs the zuko host daemon.
exec "$BIN" host --key "$KEY" --shell "$SHELL_CMD" "\$@"
EOF
chmod 0755 "$RUN"

case "$OS" in
    Linux)
        SVC_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
        mkdir -p "$SVC_DIR"
        cat >"$SVC_DIR/zuko-host.service" <<EOF
[Unit]
Description=Zuko host (interactive shell over Iroh)
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=$PREFIX/bin/zuko-host-run
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF
        echo "==> wrote $SVC_DIR/zuko-host.service"
        systemctl --user daemon-reload || true
        systemctl --user enable --now zuko-host.service || true
        echo "==> service enabled. logs: journalctl --user -u zuko-host -f"
        echo "==> ticket: journalctl --user -u zuko-host --no-pager | grep endpointa | tail -1"
        echo "==> so it runs after you log out (servers): sudo loginctl enable-linger \"$USER\""
        ;;
    Darwin)
        PLIST="$HOME/Library/LaunchAgents/dev.adonm.zuko.host.plist"
        mkdir -p "$(dirname "$PLIST")"
        cat >"$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>dev.adonm.zuko.host</string>
    <key>RunAtLoad</key><true/>
    <key>KeepAlive</key><dict><key>SuccessfulExit</key><false/></dict>
    <key>ProgramArguments</key>
    <array>
        <string>$PREFIX/bin/zuko-host-run</string>
    </array>
    <key>StandardOutPath</key><string>$HOME/.config/zuko/zuko-host.out.log</string>
    <key>StandardErrorPath</key><string>$HOME/.config/zuko/zuko-host.err.log</string>
</dict>
</plist>
EOF
        launchctl unload "$PLIST" 2>/dev/null || true
        launchctl load "$PLIST"
        echo "==> wrote $PLIST"
        echo "==> logs: tail -f $HOME/.config/zuko/zuko-host.out.log"
        echo "==> ticket: grep endpointa $HOME/.config/zuko/zuko-host.out.log | tail -1"
        ;;
    *)
        echo "==> no auto-service for $OS; run: $PREFIX/bin/zuko-host-run"
        ;;
esac

cat <<'NOTE'

zuko host setup complete. The daemon is running and will restart on reboot.

Next: connect from the Zuko iOS app, or from any terminal with `zuko` installed:

    zuko connect "<ticket>"

(the ticket is the line starting with "endpointa..." printed above).
To connect from another machine later without re-pasting, save it once:
    zuko add home "<ticket>"
then:  zuko connect home   (or just:  zuko home)

NOTE
