#!/bin/sh
# zuko host installer.
#
# Builds and installs the zuko-host daemon, then sets up a persistent
# background service (systemd user unit on Linux, launchd on macOS).
#
# Quick start (the same command the Zuko iOS app shows you):
#
#   curl -fsSL https://raw.githubusercontent.com/adonm/zuko/main/host/scripts/install.sh | sh
#
# Environment overrides:
#   ZUKO_REPO      git url            (default: https://github.com/adonm/zuko)
#   ZUKO_BRANCH    branch/tag         (default: main)
#   ZUKO_PREFIX    install prefix     (default: $HOME/.local)
#   ZUKO_KEY       secret key path    (default: $HOME/.config/zuko/key)
#   ZUKO_SHELL     shell to launch    (default: $SHELL)
set -eu

REPO="${ZUKO_REPO:-https://github.com/adonm/zuko}"
BRANCH="${ZUKO_BRANCH:-main}"
PREFIX="${ZUKO_PREFIX:-${HOME}/.local}"
KEY="${ZUKO_KEY:-${HOME}/.config/zuko/key}"
SHELL_CMD="${ZUKO_SHELL:-${SHELL:-/bin/bash}}"

need() { command -v "$1" >/dev/null 2>&1 || { echo "missing dependency: $1" >&2; exit 1; }; }
need git
need cargo
need install

OS="$(uname -s)"
ARCH="$(uname -m)"

# Make the persistent key path absolute & create config dir.
KEY="$(readlink -f "$KEY" 2>/dev/null || echo "$KEY")"
mkdir -p "$(dirname "$KEY")"
mkdir -p "$PREFIX/bin"

BUILD_DIR="$(mktemp -d)"
trap 'rm -rf "$BUILD_DIR"' EXIT

echo "==> cloning $REPO ($BRANCH)"
git clone --depth 1 --branch "$BRANCH" "$REPO" "$BUILD_DIR/zuko"

echo "==> building zuko-host (release) for $OS/$ARCH"
# shellcheck disable=SC2086
cargo build --release --manifest-path "$BUILD_DIR/zuko/host/Cargo.toml"

BIN="$PREFIX/bin/zuko-host"
install -m 0755 "$BUILD_DIR/zuko/host/target/release/zuko-host" "$BIN"
echo "==> installed $BIN"

write_run_sh() {
    # A small wrapper so the service definition is identical across platforms.
    RUN="$PREFIX/bin/zuko-host-run"
    cat >"$RUN" <<EOF
#!/bin/sh
# Generated by zuko install.sh. Edit to taste.
exec "$BIN" --key "$KEY" --shell "$SHELL_CMD" "\$@"
EOF
    chmod 0755 "$RUN"
}
write_run_sh

case "$OS" in
    Linux)
        SVC_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
        mkdir -p "$SVC_DIR"
        cat >"$SVC_DIR/zuko-host.service" <<EOF
[Unit]
Description=Zuko host (interactive shell over Iroh)
After=network-online.target
Wants=network-online.target

[Service]
ExecStart=$PREFIX/bin/zuko-host-run
Restart=on-failure
RestartSec=5

[Install]
WantedBy=default.target
EOF
        echo "==> wrote $SVC_DIR/zuko-host.service"
        systemctl --user daemon-reload || true
        systemctl --user enable --now zuko-host.service || true
        echo "==> service enabled. logs: journalctl --user -u zuko-host -f"
        echo "==> ticket: journalctl --user -u zuko-host --no-pager | grep endpointa | tail -1"
        echo "==> so it runs after you log out (servers): sudo loginctl enable-linger \"$USER\""
        ;;
    Darwin)
        PLIST="$HOME/Library/LaunchAgents/dev.adonm.zuko.host.plist"
        mkdir -p "$(dirname "$PLIST")"
        cat >"$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key><string>dev.adonm.zuko.host</string>
    <key>RunAtLoad</key><true/>
    <key>KeepAlive</key><dict><key>SuccessfulExit</key><false/></dict>
    <key>ProgramArguments</key>
    <array>
        <string>$PREFIX/bin/zuko-host-run</string>
    </array>
    <key>StandardOutPath</key><string>$HOME/.config/zuko/zuko-host.out.log</string>
    <key>StandardErrorPath</key><string>$HOME/.config/zuko/zuko-host.err.log</string>
</dict>
</plist>
EOF
        launchctl unload "$PLIST" 2>/dev/null || true
        launchctl load "$PLIST"
        echo "==> wrote $PLIST"
        echo "==> logs: tail -f $HOME/.config/zuko/zuko-host.out.log"
        echo "==> ticket: grep endpointa $HOME/.config/zuko/zuko-host.out.log | tail -1"
        ;;
    *)
        echo "==> no auto-service for $OS; run: $PREFIX/bin/zuko-host-run"
        ;;
esac

cat <<'NOTE'

zuko host setup complete. The daemon is running and will restart on reboot.

Next: in the Zuko iOS app, tap "+", give the connection a name, and paste the
ticket printed above (it starts with "endpointa...").

NOTE
