BEGIN {
  print "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
  print "<!-- Generated by scripts/generate-icons.sh from zuko-logo.png. -->"
  print "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"64\" height=\"64\" viewBox=\"0 0 64 64\">"
  print "  <defs>"
  printf "    <clipPath id=\"corners\"><rect width=\"64\" height=\"64\" rx=\"%d\"/></clipPath>\n", radius
  print "  </defs>"
  print "  <g clip-path=\"url(#corners)\" shape-rendering=\"crispEdges\">"
}

function flush_run() {
  if (run_length > 0) {
    add_run(run_x, run_y, run_length, run_color)
  }
  run_length = 0
}

function add_run(x, y, width, color, key) {
  key = color SUBSEP x SUBSEP width
  if (!(key in known_key)) {
    known_key[key] = 1
    keys[++key_count] = key
  }

  if ((key in rectangle_height) && rectangle_y[key] + rectangle_height[key] == y) {
    rectangle_height[key]++
  } else {
    if (key in rectangle_height) {
      append_rectangle(color, x, rectangle_y[key], width, rectangle_height[key])
    }
    rectangle_y[key] = y
    rectangle_height[key] = 1
  }
}

function append_rectangle(color, x, y, width, height) {
  if (!(color in known_color)) {
    known_color[color] = 1
    colors[++color_count] = color
  }
  paths[color] = paths[color] sprintf("M%d %dh%dv%dh-%dz", x, y, width, height, width)
}

$1 ~ /^[0-9]+,[0-9]+:$/ {
  coordinate = $1
  sub(/:$/, "", coordinate)
  split(coordinate, position, ",")
  x = position[1] + 0
  y = position[2] + 0
  color = substr($3, 2, 6)

  if (run_length > 0 && y == run_y && x == run_x + run_length && color == run_color) {
    run_length++
  } else {
    flush_run()
    run_x = x
    run_y = y
    run_color = color
    run_length = 1
  }
  pixel_count++
}

END {
  if (pixel_count != 4096) {
    print "pixel-svg: expected 4096 source pixels, got " pixel_count > "/dev/stderr"
    exit 1
  }
  flush_run()
  for (i = 1; i <= key_count; i++) {
    key = keys[i]
    split(key, parts, SUBSEP)
    append_rectangle(parts[1], parts[2], rectangle_y[key], parts[3], rectangle_height[key])
  }
  for (i = 1; i <= color_count; i++) {
    color = colors[i]
    printf "    <path fill=\"#%s\" d=\"%s\"/>\n", color, paths[color]
  }
  print "  </g>"
  print "</svg>"
}
