//! FFI surface for mobile clients (iOS today, Android/etc. later).
//!
//! Built as a `staticlib` and wrapped into an XCFramework that the iOS app
//! consumes via SwiftPM; the Swift bindings are generated by `uniffi-bindgen`
//! at XCFramework build time. The scaffolding lives at the crate root
//! (`src/lib.rs`); this module just holds the exported functions.
//!
//! ## Why this exists (and why it's so small)
//!
//! The one thing the iOS app can't trivially reimplement in Swift is the
//! Argon2id key derivation in [`crate::code::derive_key`]: Swift has no
//! first-party Argon2, and a third-party package would be a second
//! implementation that could drift from the Rust one (silent interop failure
//! — the derived key wouldn't match, so the iOS app would dial a different
//! NodeId than `zuko share` is serving). Rather than risk that, we expose the
//! **same function** through FFI. Bit-exactness is guaranteed by construction.
//!
//! ## uniffi version
//!
//! Pinned to 0.31 to match `iroh-ffi` — both XCFrameworks link into the same
//! iOS app, and mismatched uniffi runtimes can produce duplicate-symbol errors
//! at link time.

/// Error from the FFI handoff-key derivation. uniffi requires a proper Error
/// enum (not a bare `String`) so the Swift side gets a typed error to switch
/// on. Kept to a single variant for now — the derivation either works or it
/// doesn't, and the message carries the detail.
#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum DeriveKeyError {
    #[error("handoff key derivation failed: {message}")]
    DerivationFailed { message: String },
}

/// Derive the 32-byte handoff seed from a pairing code.
///
/// This is literally [`crate::code::derive_key`]: it normalises the code,
/// runs Argon2id (OWASP-default params, salt `b"zuko-share-handoff-v1"`),
/// and returns the 32-byte seed. The iOS app constructs an
/// `iroh::SecretKey::from_bytes(&seed)` from the result, reads its
/// `.public()` NodeId, and dials it via the N0 DNS address-lookup — exactly
/// what `handoff::claim` does on the CLI side.
///
/// The seed is returned as a `Vec<u8>` (not a fixed array) because uniffi's
/// Swift codegen maps `Vec<u8>` to `Data`, which is what the iOS side wants.
#[uniffi::export]
pub fn derive_handoff_key(code: String) -> Result<Vec<u8>, DeriveKeyError> {
    crate::code::derive_key(&code)
        .map(|sk| sk.to_bytes().to_vec())
        .map_err(|e| DeriveKeyError::DerivationFailed {
            message: format!("{e:#}"),
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Bit-exact regression guard: the seed for `tofa-mive-laru-bedo` is a
    /// fixed value computed from `src/code.rs`'s Argon2id params (OWASP
    /// defaults: m=19456 KiB, t=2, p=1, v0x13, salt `zuko-share-handoff-v1`).
    /// Captured from the Rust `argon2` crate directly, so the FFI surface —
    /// which calls the same function — must agree bit-for-bit. If this fails,
    /// the iOS app would dial the wrong NodeId and the handoff would silently
    /// never connect.
    #[test]
    fn derive_handoff_key_matches_known_vector() {
        let seed = derive_handoff_key("tofa-mive-laru-bedo".into()).unwrap();
        let expected: [u8; 32] = [
            0x8a, 0x4c, 0xb4, 0x96, 0x5b, 0x4b, 0x69, 0xb2, 0x76, 0x71, 0xcd, 0x82, 0x5a, 0xa3,
            0xe1, 0x75, 0x36, 0xe4, 0xba, 0x90, 0xeb, 0xf3, 0x91, 0x00, 0x42, 0x83, 0x9c, 0xf3,
            0x8b, 0x16, 0x49, 0x8e,
        ];
        assert_eq!(
            seed, expected,
            "FFI seed drifted from the captured vector — iOS interop will break"
        );
    }

    /// Same seed must emerge regardless of how the code is formatted
    /// (case, separators), because `normalize_code` strips all of that.
    #[test]
    fn derive_handoff_key_is_separator_and_case_agnostic() {
        let canonical = derive_handoff_key("tofa-mive-laru-bedo".into()).unwrap();
        let messy = derive_handoff_key("TOFA MIVE LARU BEDO".into()).unwrap();
        assert_eq!(canonical, messy);
    }
}
