//! FFI surface for the iOS client.
//!
//! Built as a `staticlib` and wrapped into an XCFramework that the iOS app
//! consumes via SwiftPM; the Swift bindings are generated by `uniffi-bindgen`
//! at XCFramework build time. The scaffolding lives at the crate root
//! (`src/lib.rs`); this module just holds the exported functions.
//!
//! ## Why this exists (and why it's so small)
//!
//! The one thing the iOS app can't trivially reimplement in Swift is the
//! Argon2id key derivation in [`crate::code::derive_key`]: Swift has no
//! first-party Argon2, and a third-party package would be a second
//! implementation that could drift from the Rust one (silent interop failure
//! — the derived key wouldn't match, so the iOS app would dial a different
//! NodeId than `zuko share` is serving). Rather than risk that, we expose the
//! **same function** through FFI. Bit-exactness is guaranteed by construction.
//!
//! ## uniffi version
//!
//! Pinned to 0.31 to match `iroh-ffi` — both XCFrameworks link into the same
//! iOS app, and mismatched uniffi runtimes can produce duplicate-symbol errors
//! at link time.

/// Error from the FFI handoff-key derivation. uniffi requires a proper Error
/// enum (not a bare `String`) so the Swift side gets a typed error to switch
/// on. Kept to a single variant for now — the derivation either works or it
/// doesn't, and the message carries the detail.
#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum DeriveKeyError {
    #[error("handoff key derivation failed: {message}")]
    DerivationFailed { message: String },
}

/// Derive the 32-byte handoff seed from a pairing code.
///
/// This is literally [`crate::code::derive_seed`]: it normalises the code,
/// runs Argon2id (OWASP-default params, salt `b"zuko-share-handoff-v1"`),
/// and returns the 32-byte seed. The iOS app constructs an
/// `iroh::SecretKey::from_bytes(&seed)` from the result, reads its
/// `.public()` NodeId, and dials it via the N0 DNS address-lookup — exactly
/// what `handoff::claim` does on the CLI side.
///
/// The seed is returned as a `Vec<u8>` (not a fixed array) because uniffi's
/// Swift codegen maps `Vec<u8>` to `Data`, which is what the iOS side wants.
///
/// Uses `derive_seed` (not `derive_key`) so the iOS staticlib doesn't need
/// to depend on `iroh` — the seed is plain bytes, and the iOS app already
/// wraps them in `IrohLib.SecretKey.fromBytes`. Keeps `iroh` (and its
/// transitive `ring` C/asm dep) out of the iOS staticlib, which is what
/// lets `build-ffi.sh` cross-compile from Linux without `xcrun`.
#[uniffi::export]
pub fn derive_handoff_key(code: String) -> Result<Vec<u8>, DeriveKeyError> {
    crate::code::derive_seed(&code)
        .map(|seed| seed.to_vec())
        .map_err(|e| DeriveKeyError::DerivationFailed {
            message: format!("{e:#}"),
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Bit-exact regression guard: the seed for `iridescent-hilton` (a valid
    /// petname large adjective+noun code) is a fixed value computed from
    /// `src/code.rs`'s Argon2id params (OWASP defaults: m=19456 KiB, t=2,
    /// p=1, v0x13, salt `zuko-share-handoff-v1`). Captured from the Rust
    /// `argon2` crate directly, so the FFI surface — which calls the same
    /// function — must agree bit-for-bit. If this fails, the iOS app would
    /// dial the wrong NodeId and the handoff would silently never connect.
    #[test]
    fn derive_handoff_key_matches_known_vector() {
        let seed = derive_handoff_key("iridescent-hilton".into()).unwrap();
        let expected: [u8; 32] = [
            0x52, 0x83, 0xf4, 0xc1, 0x4a, 0xfc, 0xfa, 0xb6, 0x36, 0x41, 0xcd, 0x2e, 0x49, 0x61,
            0xe9, 0x31, 0x88, 0x89, 0xde, 0xe8, 0xce, 0x65, 0x07, 0x8b, 0x56, 0xd3, 0x7d, 0x82,
            0x41, 0x18, 0x80, 0x8e,
        ];
        assert_eq!(
            seed, expected,
            "FFI seed drifted from the captured vector — iOS interop will break"
        );
    }

    /// Same seed must emerge regardless of how the code is formatted
    /// (case, separators), because `normalize_code` strips all of that.
    #[test]
    fn derive_handoff_key_is_separator_and_case_agnostic() {
        let canonical = derive_handoff_key("iridescent-hilton".into()).unwrap();
        let messy = derive_handoff_key("IRIDESCENT HILTON".into()).unwrap();
        assert_eq!(canonical, messy);
    }
}
